- Introduction
- Installation
- Ndarray
- Data Types
- Numpy Array
- Indexing and Slicing
- Broadcasting
- Binary Operator
- String Function
- Mathematical Function
- Airthmetic Function
- Statistical Function
- Linear Algebra

### Introduction

> Numpy stands for Numerical Python. NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

> At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous
data types, with many operations being performed in compiled code for performance. 

> There are several important differences between NumPy arrays and the standard Python sequences:
>- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the
size of an ndarray will create a new array and delete the original.
> - The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in
memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays
of different sized elements.
> - NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in
sequences.
> - A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though
these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing,
and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most)
of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence
types is insufficient - one also needs to know how to use NumPy arrays.


### Why Numpy is fast?

> Numpy arrays are densely packed arrays of homogeneous type. Python lists, by contrast, are arrays of pointers to objects, even when all of them are of the same type. So, you get the benefits of locality of reference.

>Also, many Numpy operations are implemented in C, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing, but a few orders of magnitude isn't uncommon in number crunching programs.

In [9]:
from time import time
import numpy as np
numpy_array = np.random.rand(100000)
list_conv = list(numpy_array)

start1 = time()
numpy_mean = np.mean(numpy_array)
print(numpy_mean)
end = time()
time_taken = end - start1
print("Numpy", time_taken)

start_2 = time()
list_mean = np.mean(list_conv)
print(list_mean)
end2= time()
time_take_2 = end2-start_2
print("list", time_take_2)

0.5004489677693271
Numpy 0.0019965171813964844
0.5004489677693271
list 0.005956888198852539


### Installation
`pip install numpy`

### Basic - Ndarray

Numpy main object is the homogeneous multidimensional array. It is a table of element (usually number), all of the same type. In Numpy dimension are called axes.

For example the coordinate of point in 3D space `[1, 2, 3]` has one axis. This axis has three element in it so we say that length of 3

Numpy's array class is called ndarray. It is also known as the alias array.

- `ndarray.ndim`  the number of axes (dimensions) of the array.
    - **0-D array:**- O-D array is also called scalar, are simple element in the array (It has only element)
    
    - **1-D array:**- 1-D array is also called vector or uni-dimensional array (it has 1-D array as element)
    
    - **2-D array:**- 2-D array is also called matrix or 2nd order tensor (It has 1-D array as element)
    
    - **3-D array:**- 3-D array is also called 3rd order tensor or more than and equal to 3-D array called tensor (it has 2-D array as element)
    

- `ndarray.shape` the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.  
For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is
therefore the number of axes, ndim.


- `ndarray.size` the total number of elements of the array. This is equal to the product of the elements of shape.


- `ndarray.dtype` an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and
numpy.float64 are some examples.


- `ndarray.itemsize` the size in bytes of each element of the array. For example, an array of elements of type float64
has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to
ndarray.dtype.itemsize.


- `ndarray.data` the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute
because we will access the elements in an array using indexing facilities.

In [1]:
import numpy as np

In [2]:
a = np.arange(16).reshape(2, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [3]:
a.shape

(2, 8)

In [4]:
a.ndim

2

In [5]:
a.dtype

dtype('int32')

In [6]:
a.itemsize

4

In [7]:
a.size

16

In [8]:
type(a)

numpy.ndarray

### Array Creation

1. we can create an array by the different ways
2. array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into
three-dimensional arrays, and so on.

>Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to
create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.
The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function
empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype
of the created array is float64.

##### Arange vs Linespace

>When arange is used with floating point arguments, it is generally not possible to predict the number of elements
obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace
that receives as an argument the number of elements that we want, instead of the step:


In [50]:
ar = np.array([1,3,4,5])
ar

array([1, 3, 4, 5])

In [51]:
type(ar), ar.dtype

(numpy.ndarray, dtype('int32'))

In [52]:
arr_1 = np.array([(1.5,2,3), (4,5,6)])
arr_1

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [53]:
zero_array = np.zeros( (3,4) )
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
ones_array = np.ones( (3,4), dtype = np.int32)
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [55]:
ones_array.dtype

dtype('int32')

In [10]:
empty_array = np.empty((6,3))
empty_array

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306],
       [1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306],
       [1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307],
       [9.34609790e-307, 3.91792279e-317, 0.00000000e+000]])

In [57]:
arr_2 = np.arange(4, 20, 2)
arr_2

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
arr_3 = np.linspace( 0, 2, 9 )
arr_3

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

### Indexing Slicing and Iterating

ndarry can be indexing using standard python way x[obj] syntax where x is arra and obj is the selection, element inside ndarray follows zero based index

**Slicing:** Slicing in ndarray also work as python slicing `[start:stop:steps]`, by default `start` value is `0th index` `stop` is end length of array that means index would be n-1 where n is length of array, and `step` will take `1` at a time


**Iterating** Iterating over multidimensional arrays is done with respect to the first axis

In [30]:
arr_4 = np.arange(10)
arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#5th element
arr_4[4]

4

In [34]:
#slcing
arr_5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr_5[2:9])

[3 4 5 6 7 8 9]


In [35]:
#Negative Indexing
print(arr_5[-4:-1])

[6 7 8]


In [36]:
# Steps
print(arr_5[2:9:2])

[3 5 7 9]


In [38]:
arr_6 = np.arange(20).reshape(5, 4)
arr_6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
for i in arr_6:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


In [41]:
# flat iterate on each of the element
for i in arr_6.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [59]:
arr_7 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr_7):
    print(x)

1
2
3
4
5
6
7
8


In [60]:
arr_8 = np.array([1, 2, 3])

for x in np.nditer(arr_8, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [61]:
arr_9 = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr_9):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [62]:
arr_10 = np.array([1, 2, 3])

arr_11 = np.array([4, 5, 6])

arr_12 = np.concatenate((arr_10, arr_11))

print(arr_12)

[1 2 3 4 5 6]


In [63]:
arr_13 = np.array([[1, 2], [3, 4]])

arr_14 = np.array([[5, 6], [7, 8]])

arr_15 = np.concatenate((arr_13, arr_14), axis=1)

print(arr_15)

[[1 2 5 6]
 [3 4 7 8]]


In [71]:
arr_16 = np.array([1, 2, 3])

arr_17 = np.array([4, 5, 6])

arr_18 = np.stack((arr_16, arr_17), axis=1)

print(arr_18)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
arr_16 = np.array([1, 2, 3])

arr_17 = np.array([4, 5, 6])

arr_18 = np.stack((arr_16, arr_17), axis=0)

print(arr_18)

[[1 2 3]
 [4 5 6]]


In [72]:
arr_19 = np.array([1, 2, 3, 4, 5, 6])

arr_20 = np.array_split(arr_19, 3)
arr_20

[array([1, 2]), array([3, 4]), array([5, 6])]

In [73]:
print(np.sort(arr_19))

[1 2 3 4 5 6]


### Broadcasting

>The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed

>If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.



In [75]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:') 
print (a) 
  
print('Second array:') 
print(b)

print('First Array + Second Array' )
print(a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
[1. 2. 3.]
First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
